controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /authentication_token
    methods: ['POST']

register:
    path: /api/register
    methods: POST
    controller: App\Controller\RegistrationController::create
